"""Add billing_address_id to Order model

Revision ID: 066dcb04b034
Revises: 674f6f3523fc
Create Date: 2025-03-22 21:20:20.359715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066dcb04b034'
down_revision: Union[str, None] = '674f6f3523fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('billing_address_id', sa.Integer(), nullable=False))
    
    # Check if the enum type already exists
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'orderstatus') THEN "
               "CREATE TYPE orderstatus AS ENUM ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED'); "
               "END IF; END $$;")
    
    # First update all existing values to ensure they match enum values
    op.execute("UPDATE orders SET status = 'PENDING' WHERE status NOT IN ('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')")
    
    # Now convert using proper CAST
    op.execute("ALTER TABLE orders ALTER COLUMN status TYPE orderstatus USING status::orderstatus")
    
    op.create_foreign_key(op.f('fk_orders_billing_address_id_addresses'), 'orders', 'addresses', ['billing_address_id'], ['id'])
    op.alter_column('users', 'artist_bio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'artist_bio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_orders_billing_address_id_addresses'), 'orders', type_='foreignkey')
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('orders', 'billing_address_id')
    # ### end Alembic commands ###
