"""Add payment_status and fix updated_at fields

Revision ID: 4b217353e1f3
Revises: c10e36ad8a88
Create Date: 2025-03-22 22:04:11.074912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b217353e1f3'
down_revision: Union[str, None] = 'c10e36ad8a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    # Add nullable column first
    op.add_column('orders', sa.Column('payment_status', sa.String(), nullable=True))
    
    # Update existing records to set payment_status to "pending"
    op.execute("UPDATE orders SET payment_status = 'pending'")
    
    # Now set the column to NOT NULL
    op.alter_column('orders', 'payment_status', nullable=False)
    
    op.add_column('orders', sa.Column('payment_intent_id', sa.String(), nullable=True))
    
    # Ensure default value for updated_at in orders
    op.execute("UPDATE orders SET updated_at = created_at WHERE updated_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_intent_id')
    op.drop_column('orders', 'payment_status')
    op.drop_column('order_items', 'updated_at')
    # ### end Alembic commands ###
