"""add reviewer_name to reviews

Revision ID: 674f6f3523fc
Revises: remove_artist_business_fields
Create Date: 2025-03-22 11:48:41.920431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674f6f3523fc'
down_revision: Union[str, None] = 'remove_artist_business_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('reviewer_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'reviewer_name')
    # ### end Alembic commands ###
