"""Add subtotal, shipping_cost, and tax to Order model

Revision ID: 94b7a4e59d7e
Revises: 066dcb04b034
Create Date: 2025-03-22 21:32:32.290274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b7a4e59d7e'
down_revision: Union[str, None] = '066dcb04b034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('subtotal', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipping_cost', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('tax', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tax')
    op.drop_column('orders', 'shipping_cost')
    op.drop_column('orders', 'subtotal')
    # ### end Alembic commands ###
