"""Add full_name and phone_number to Address model

Revision ID: c10e36ad8a88
Revises: 94b7a4e59d7e
Create Date: 2025-03-22 21:51:09.318410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10e36ad8a88'
down_revision: Union[str, None] = '94b7a4e59d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'phone_number')
    op.drop_column('addresses', 'full_name')
    # ### end Alembic commands ###
