"""Add artist_id to Product model

Revision ID: d42b47ca387e
Revises: 4b217353e1f3
Create Date: 2025-03-25 10:05:02.026526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42b47ca387e'
down_revision: Union[str, None] = '4b217353e1f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('artist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_products_artist_id_users'), 'products', 'users', ['artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_products_artist_id_users'), 'products', type_='foreignkey')
    op.drop_column('products', 'artist_id')
    # ### end Alembic commands ###
