variable "env" {}
variable "cust_name" {}
variable "stage_name" {}
variable "ecs_family" {}
variable "vpc_id" {} 
variable "health_path" {}
variable "tags" {}
variable "ecs_service_id" {}
variable "deployment_type" {}
